# This file contains the configuration settings for the data processing pipeline

specific_words: # Words to filter by
  - "president"
  - "the"
  - "Asia"

log_file: "logs/data_processed.txt" # Path to the log file

dataset_split: "test" # Test or train dataset

output_format: "parquet" # Output format for the processed data

spark_settings: # Spark settings
  cores: 4
  driver_memory: "4g"
  executor_memory: "4g"
